server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    loadbalancer:
      configurations: round-robin
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      server:
        webflux:
          routes:
            - id: customer-management
              uri: lb://CUSTOMER-MANAGEMENT
              predicates:
                - Path=/rest/api/customers/v1/**,/h2-console/**
            - id: account-management
              uri: lb://ACCOUNT-MANAGEMENT
              predicates:
                - Path=/rest/api/account/v1/**