server:
  port: 8080

spring:
  application:
    name: api-gateway
  reactor:
    context-propagation: AUTO
  cloud:
    gateway:
      loadbalancer:
        configurations: round-robin
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: customer-management
              uri: lb://CUSTOMER-MANAGEMENT
              predicates:
                - Path=/rest/api/customers/v1/**
            - id: customer-management-actuator
              uri: lb://CUSTOMER-MANAGEMENT
              predicates:
                - Path=/customer-management/actuator/**
              filters:
                  - RewritePath=/customer-management/actuator/(?<segment>.*), /actuator/${segment}
            - id: customer-management-database
              uri: lb://CUSTOMER-MANAGEMENT
              predicates:
                - Path=/customer-management/db/**
              filters:
                - RewritePath=/customer-management/db/**(?<segment>.*), /db/${segment}
            - id: account-management
              uri: lb://ACCOUNT-MANAGEMENT
              predicates:
                - Path=/rest/api/account/v1/**
            - id: account-management-all
              uri: lb://ACCOUNT-MANAGEMENT
              predicates:
                - Path=/account-management/db/h2-console/**,/account-management/actuator/**
              filters:
                - StripPrefix=1