server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      loadbalancer:
        configurations: round-robin
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: customer-management
              uri: lb://customer-management
              predicates:
                - Path=/rest/api/customers/v1/**,/customer-management/db/h2-console/**,/customer-management/actuator/**
            - id: account-management
              uri: lb://ACCOUNT-MANAGEMENT
              predicates:
                - Path=/rest/api/account/v1/**,/account-management/db/h2-console/**,/account-management/actuator/**