server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    config:
      name: eureka-client,logging,actuator
    gateway:
      server:
        webflux:
          routes:
            - id: customer-management
              uri: lb://customer-management
              predicates:
                - Path=/rest/api/customers/v1/**
            - id: h2-console
              uri: lb://customer-management
              predicates:
                - Path=/h2-console/**