server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: customer-management
              uri: lb://customer-management
              predicates:
                - Path=/customers/**
            - id: h2-console
              uri: lb://customer-management
              predicates:
                - Path=/h2-console/**