spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/businessDB
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true