spring:
  datasource:
    url: jdbc:h2:file:~/businessDB;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false

  flyway:
    enabled: true