eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://localhost:8761/eureka/
    metadata-map:
      port: ${server.port}
spring:
  cloud:
    service-registry:
      auto-registration:
        enabled: false