tracing:
  enabled: true
  sampling:
    probability: 1.0   # 100% traces (reduce in prod)
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
management:
  tracing:
    enabled: true
    propagation:
      produce: b3
      consume: b3
spring:
  cloud:
    openfeign:
      micrometer:
        enabled: true
